// <auto-generated />
namespace SMS_WebAPI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addstudentgenderandremovebrothers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstudentgenderandremovebrothers));
        
        string IMigrationMetadata.Id
        {
            get { return "201412211050000_add student.gender and remove brothers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
