// <auto-generated />
namespace SMS_WebAPI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class parentsinsteadofparent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(parentsinsteadofparent));
        
        string IMigrationMetadata.Id
        {
            get { return "201412200949327_parents instead of parent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
