// <auto-generated />
namespace SMS_WebAPI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class grade_language : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(grade_language));
        
        string IMigrationMetadata.Id
        {
            get { return "201412161429264_grade_language"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
